// <auto-generated />
namespace First_Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class seedusers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seedusers));
        
        string IMigrationMetadata.Id
        {
            get { return "202112102335320_seedusers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
