// <auto-generated />
namespace First_Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class date_in_category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(date_in_category));
        
        string IMigrationMetadata.Id
        {
            get { return "202111131923044_date_in_category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
